import { Platform, Share, PermissionsAndroid, Alert, Linking } from 'react-native';
import RNFS from 'react-native-fs';
import ShareRN from 'react-native-share';
import * as XLSX from 'xlsx';
import AsyncStorage from '@react-native-async-storage/async-storage';
// pdf-lib is loaded dynamically to avoid build errors if not installed yet

/**
 * Convert data to CSV format
 */
const convertToCSV = (data: any[], headers?: string[]): string => {
    if (!Array.isArray(data) || data.length === 0) {
        return '';
    }

    const dataArray = Array.isArray(data) ? data : [data];
    const cols = headers || Object.keys(dataArray[0]);

    const headerRow = cols.map(col => `"${col}"`).join(',');
    const dataRows = dataArray.map(row =>
        cols.map(col => {
            const value = row[col];
            if (value === null || value === undefined) {
                return '';
            }
            const stringValue = String(value).replace(/"/g, '""');
            return `"${stringValue}"`;
        }).join(',')
    );

    return [headerRow, ...dataRows].join('\n');
};

/**
 * Convert data to HTML format (viewable in browser or email)
 */
const convertToHTML = (data: any, title: string): string => {
    const dataArray = Array.isArray(data) ? data : [data];

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 40px 20px;
      min-height: 100vh;
    }
    .container {
      max-width: 1200px;
      margin: 0 auto;
      background: white;
      border-radius: 12px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #007AFF 0%, #0051BA 100%);
      color: white;
      padding: 40px;
      text-align: center;
    }
    .header h1 {
      font-size: 32px;
      margin-bottom: 10px;
    }
    .header p {
      font-size: 14px;
      opacity: 0.9;
    }
    .content {
      padding: 40px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 40px;
    }
    th {
      background-color: #f5f5f5;
      color: #333;
      padding: 15px;
      text-align: left;
      font-weight: 600;
      border-bottom: 3px solid #007AFF;
      font-size: 13px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    td {
      padding: 12px 15px;
      border-bottom: 1px solid #e0e0e0;
      font-size: 14px;
      color: #333;
    }
    tr:hover {
      background-color: #f9f9f9;
    }
    tr:last-child td {
      border-bottom: none;
    }
    .summary {
      background: linear-gradient(135deg, #e8f4f8 0%, #f0ecff 100%);
      border-left: 5px solid #007AFF;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    .summary h3 {
      color: #007AFF;
      margin-bottom: 10px;
      font-size: 16px;
    }
    .summary p {
      margin: 8px 0;
      color: #555;
      font-size: 13px;
    }
    .footer {
      text-align: center;
      padding: 30px;
      background: #f9f9f9;
      color: #999;
      font-size: 12px;
      border-top: 1px solid #e0e0e0;
    }
    .footer p {
      margin: 5px 0;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>${title}</h1>
      <p>Report generated on ${new Date().toLocaleString()}</p>
    </div>
    <div class="content">
      <div class="summary">
        <h3>Report Summary</h3>
        <p><strong>Total Records:</strong> ${dataArray.length}</p>
        <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
      </div>
      <table>
        <thead>
          <tr>
            ${Object.keys(dataArray[0]).map(key => `<th>${key}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${dataArray.map((row, idx) => `
            <tr>
              ${Object.values(row).map(value => `<td>${value || 'N/A'}</td>`).join('')}
            </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    <div class="footer">
      <p>This report was auto-generated by the Locum Healthcare App</p>
      <p>${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
    </div>
  </div>
</body>
</html>
  `;

    return htmlContent;
};


// Request write permissions for Android external storage (legacy devices)
const ensureAndroidDownloadPermission = async (): Promise<void> => {
    if (Platform.OS !== 'android') return;
    try {
        const perms: string[] = [];
        if (PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE) {
            perms.push(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);
        }
        if (PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE) {
            perms.push(PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE);
        }
        if (perms.length === 0) return;
        const res = await PermissionsAndroid.requestMultiple(perms as any);
        const denied = Object.values(res).some((v) => v !== PermissionsAndroid.RESULTS.GRANTED);
        if (denied) {
            throw new Error('Storage permission denied');
        }
    } catch (e) {
        // If request API not available, proceed and let write fail if not permitted
    }
};

// PDF generation removed: migrate to server-generated PDFs or view with react-native-pdf

/**
 * Download a PDF from a remote URL to device storage and prompt to open it
 */
export const downloadPDF = async (url: string, fileName: string): Promise<void> => {
    try {
        // Ensure Android permissions on legacy devices
        await ensureAndroidDownloadPermission();

        // Resolve auth headers (Bearer token) if present
        const token = await AsyncStorage.getItem('jwt_token');
        const headers: Record<string, string> = {
            Accept: 'application/pdf',
        };
        if (token) {
            headers.Authorization = `Bearer ${token}`;
        }

        // Choose a writable destination within the app sandbox
        const destinationPath = `${RNFS.DocumentDirectoryPath}/${fileName}.pdf`;

        // Helper to try a single URL
        const tryDownload = async (u: string) => {
            const download = RNFS.downloadFile({ fromUrl: u, toFile: destinationPath, headers });
            const res = await download.promise;
            return res.statusCode;
        };

        // Try original URL; if 404, attempt common variants
        let status = await tryDownload(url);
        if (status === 404) {
            const variants: string[] = [];
            if (url.endsWith('.pdf')) {
                variants.push(url.replace(/\.pdf$/, '/pdf'));
                variants.push(url.replace(/\.pdf$/, '?format=pdf'));
            } else if (url.endsWith('/pdf')) {
                variants.push(url.replace(/\/pdf$/, '.pdf'));
                variants.push(`${url.replace(/\/pdf$/, '')}?format=pdf`);
            } else if (!/format=pdf/.test(url)) {
                variants.push(`${url}${url.includes('?') ? '&' : '?'}format=pdf`);
                variants.push(`${url}${url.endsWith('/') ? '' : '/'}pdf`);
            }

            for (const alt of variants) {
                status = await tryDownload(alt);
                if (status === 200) break;
            }
        }

        if (status !== 200) {
            throw new Error(`Download failed with status ${status}`);
        }

        // Prompt to open
        Alert.alert(
            'Download Complete',
            'PDF downloaded successfully. Would you like to open it?',
            [
                { text: 'Cancel', style: 'cancel' },
                {
                    text: 'Open',
                    onPress: async () => {
                        try {
                            await ShareRN.open({
                                url: `file://${destinationPath}`,
                                type: 'application/pdf',
                            });
                        } catch (err) {
                            // user may cancel share sheet; ignore
                        }
                    },
                },
            ]
        );
    } catch (error) {
        console.error('Download error:', error);
        Alert.alert('Download Failed', 'Could not download the PDF file');
    }
};

/**
 * Try multiple URLs (in order) to download a PDF. Each URL will also attempt
 * common variants (.pdf, /pdf, ?format=pdf) with auth headers.
 */
export const downloadPDFMulti = async (urls: string[], fileName: string): Promise<void> => {
    let lastError: any = null;
    for (const candidate of urls) {
        try {
            await downloadPDF(candidate, fileName);
            return; // success
        } catch (e) {
            lastError = e;
        }
    }
    throw lastError || new Error('Failed to download PDF from all candidates');
};

/**
 * Generate a simple PDF (title + table) client-side and save to device.
 * rows: array of objects
 * columns: ordered list of keys to include
 */
export const generateAndSavePDF = async (
    rows: any[],
    fileName: string,
    columns: string[],
    title: string = 'Report'
): Promise<string> => {
    // Ensure Android storage permission on legacy devices when we try to copy to Downloads
    await ensureAndroidDownloadPermission();
    const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
    const safeRows = Array.isArray(rows) ? rows : [rows];
    const pdfDoc = await PDFDocument.create();
    const A4 = { w: 595.28, h: 841.89 };
    let page = pdfDoc.addPage([A4.w, A4.h]);
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const margin = { top: 40, right: 40, bottom: 40, left: 40 };
    const headerGap = 10;
    const bodyFontSize = 10;
    const headerFontSize = 11;
    const lineHeight = 14;
    const usableWidth = A4.w - margin.left - margin.right;
    const colCount = Math.max(columns.length, 1);
    const colWidth = usableWidth / colCount;
    const cellPadding = 4;

    let cursorY = A4.h - margin.top;

    const drawHeader = () => {
        // Title
        page.drawText(title, { x: margin.left, y: cursorY, size: 18, font: bold, color: rgb(0.1, 0.1, 0.1) });
        cursorY -= 24;
        const generated = `Generated: ${new Date().toLocaleString()}`;
        page.drawText(generated, { x: margin.left, y: cursorY, size: 10, font, color: rgb(0.4, 0.4, 0.4) });
        cursorY -= 20;

        // Table header background
        const headerY = cursorY + lineHeight + 2;
        page.drawRectangle({ x: margin.left, y: headerY - lineHeight - 4, width: usableWidth, height: lineHeight + 6, color: rgb(0.95, 0.95, 0.97) });

        // Column titles
        columns.forEach((key, i) => {
            const x = margin.left + i * colWidth + cellPadding;
            page.drawText(String(key), { x, y: cursorY, size: headerFontSize, font: bold, color: rgb(0.2, 0.2, 0.3) });
        });
        cursorY -= headerGap + lineHeight;
        // Divider line
        page.drawLine({ start: { x: margin.left, y: cursorY }, end: { x: margin.left + usableWidth, y: cursorY }, thickness: 1, color: rgb(0.85, 0.85, 0.9) });
        cursorY -= 6;
    };

    const wrapText = (text: string, maxWidth: number) => {
        if (!text) return [''];
        const words = String(text).split(/\s+/);
        const lines: string[] = [];
        let current = '';
        for (const w of words) {
            const test = current ? `${current} ${w}` : w;
            const width = font.widthOfTextAtSize(test, bodyFontSize);
            if (width <= maxWidth) {
                current = test;
            } else {
                if (current) lines.push(current);
                // If single word too long, hard cut
                const wordWidth = font.widthOfTextAtSize(w, bodyFontSize);
                if (wordWidth > maxWidth) {
                    let piece = '';
                    for (const ch of w) {
                        const next = piece + ch;
                        if (font.widthOfTextAtSize(next, bodyFontSize) > maxWidth) {
                            lines.push(piece);
                            piece = ch;
                        } else {
                            piece = next;
                        }
                    }
                    current = piece;
                } else {
                    current = w;
                }
            }
        }
        if (current) lines.push(current);
        return lines;
    };

    const ensureSpace = (needed: number) => {
        if (cursorY - needed < margin.bottom) {
            page = pdfDoc.addPage([A4.w, A4.h]);
            cursorY = A4.h - margin.top;
            drawHeader();
        }
    };

    // Start with header
    drawHeader();

    // Render rows with wrapping, computing row height by max cell lines
    for (const row of safeRows) {
        // Prepare cell lines
        const cellLines: string[][] = columns.map((key) => wrapText(row[key] === null || row[key] === undefined ? '' : String(row[key]), colWidth - cellPadding * 2));
        const maxLines = cellLines.reduce((m, lines) => Math.max(m, lines.length), 1);
        const rowHeight = maxLines * lineHeight + 6; // padding
        ensureSpace(rowHeight + 2);

        // Optional zebra background
        page.drawRectangle({ x: margin.left, y: cursorY - (rowHeight - 6), width: usableWidth, height: rowHeight - 6, color: rgb(0.99, 0.99, 1) });

        // Draw each cell
        cellLines.forEach((lines, i) => {
            const x = margin.left + i * colWidth + cellPadding;
            let y = cursorY;
            for (const line of lines) {
                page.drawText(line, { x, y, size: bodyFontSize, font, color: rgb(0.1, 0.1, 0.12) });
                y -= lineHeight;
            }
        });

        cursorY -= rowHeight;
    }

    const pdfBytes: Uint8Array = await pdfDoc.save();

    // Ensure dir exists
    try {
        const exists = await RNFS.exists(RNFS.DocumentDirectoryPath);
        if (!exists) await RNFS.mkdir(RNFS.DocumentDirectoryPath);
    } catch { }

    // Convert to base64
    const toBase64 = (bytes: Uint8Array): string => {
        const base64js = require('base64-js');
        return base64js.fromByteArray(bytes);
    };

    const outPath = `${RNFS.DocumentDirectoryPath}/${fileName}.pdf`;
    await RNFS.writeFile(outPath, toBase64(pdfBytes), 'base64');

    // Best-effort copy to public Downloads on Android, then media-scan
    let finalPath = outPath;
    if (Platform.OS === 'android') {
        try {
            const dl = (RNFS as any).DownloadDirectoryPath;
            if (dl) {
                const publicPath = `${dl}/${fileName}.pdf`;
                await RNFS.copyFile(outPath, publicPath).catch(() => { });
                finalPath = publicPath;
                try {
                    await (RNFS as any).scanFile([{ path: publicPath, mime: 'application/pdf' }]);
                } catch { }
            } else {
                // At least scan the app path so file managers can find it
                try {
                    await (RNFS as any).scanFile([{ path: outPath, mime: 'application/pdf' }]);
                } catch { }
            }
        } catch { }
    }

    // Offer to open
    try {
        await ShareRN.open({ url: `file://${finalPath}`, type: 'application/pdf' });
    } catch { }

    return finalPath;
};

/**
 * Create an XLSX file from JSON rows and return the file path
 */
export const exportToXLSXFile = async (
    rows: any[],
    fileName: string,
    headers?: string[]
): Promise<string> => {
    try {
        // Ensure permissions for Android when writing to Downloads
        await ensureAndroidDownloadPermission();
        const safeRows = Array.isArray(rows) ? rows : [rows];
        const cols = headers && headers.length > 0 ? headers : Object.keys(safeRows[0] || {});

        const normalizedRows = safeRows.map((row) => {
            const out: Record<string, any> = {};
            cols.forEach((key) => {
                out[key] = row[key];
            });
            return out;
        });

        const worksheet = XLSX.utils.json_to_sheet(normalizedRows, { header: cols });
        const workbook = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(workbook, worksheet, 'Report');
        const base64 = XLSX.write(workbook, { type: 'base64', bookType: 'xlsx' });

        // Write to app's Documents directory (always writable)
        const xlsxPath = `${RNFS.DocumentDirectoryPath}/${fileName}.xlsx`;

        // Ensure directory exists
        try {
            const exists = await RNFS.exists(RNFS.DocumentDirectoryPath);
            if (!exists) {
                await RNFS.mkdir(RNFS.DocumentDirectoryPath);
            }
        } catch (err) {
            console.log('Directory check error:', err);
        }

        // Write the file
        await RNFS.writeFile(xlsxPath, base64, 'base64');

        // Verify file was created
        const fileExists = await RNFS.exists(xlsxPath);
        if (!fileExists) {
            throw new Error('File was not created successfully');
        }

        console.log('✅ Excel file created at:', xlsxPath);

        // Prefer sharing a public Downloads copy on Android so external apps can access it
        let sharePath = xlsxPath;
        if (Platform.OS === 'android') {
            try {
                const dl = (RNFS as any).DownloadDirectoryPath;
                if (dl) {
                    const publicPath = `${dl}/${fileName}.xlsx`;
                    await RNFS.copyFile(xlsxPath, publicPath).catch(() => { });
                    sharePath = publicPath;
                    try {
                        await (RNFS as any).scanFile([{ path: publicPath, mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }]);
                    } catch { }
                }
            } catch { }
        }

        // Share immediately (same UX as PDF)
        const mime = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
        const url = `file://${sharePath}`;
        try {
            await ShareRN.open({ url, type: mime, failOnCancel: false, showAppsToView: true });
        } catch (e1) {
            try {
                await ShareRN.open({ urls: [url], type: mime, failOnCancel: false, showAppsToView: true });
            } catch (e2) {
                try {
                    await Linking.openURL(url);
                } catch { throw e2; }
            }
        }

        return xlsxPath;
    } catch (error) {
        console.error('Excel export error:', error);
        throw error;
    }
};

/**
 * Export data to PDF/HTML (via Share API)
 * This opens the share sheet allowing user to send via email, save, etc.
 */
export const exportToPDF = async (
    data: any,
    fileName: string,
    title: string = 'Report'
): Promise<void> => {
    try {
        const dataArray = Array.isArray(data) ? data : [data];

        // Create a summary message for sharing
        let message = `${title}\n\n`;
        message += `Generated: ${new Date().toLocaleString()}\n`;
        message += `Total Records: ${dataArray.length}\n\n`;

        // Add first few records as preview
        if (dataArray.length > 0) {
            const firstRecord = dataArray[0];
            message += 'Data Preview:\n';
            Object.entries(firstRecord).forEach(([key, value]) => {
                message += `${key}: ${value}\n`;
            });
        }

        const result = await Share.share({
            message: message,
            title: `${fileName} - Report`,
            url: undefined,
        });

        if (result.action === Share.dismissedAction) {
            console.log('Share dismissed');
        }
    } catch (error) {
        console.error('Error exporting to PDF:', error);
        throw error;
    }
};

/**
 * Export data to Excel/CSV (via Share API with data preview)
 */
export const exportToExcel = async (
    data: any[],
    fileName: string,
    headers?: string[]
): Promise<void> => {
    try {
        const dataArray = Array.isArray(data) ? data : [data];

        // Create CSV format for better Excel compatibility
        const cols = headers || Object.keys(dataArray[0] || {});
        const csvData = [
            cols.join(','),
            ...dataArray.map(row =>
                cols.map(col => {
                    const value = row[col];
                    if (value === null || value === undefined) return '';
                    return `"${String(value).replace(/"/g, '""')}"`;
                }).join(',')
            )
        ].join('\n');

        // Create summary message
        let message = `Excel Export: ${fileName}\n\n`;
        message += `Generated: ${new Date().toLocaleString()}\n`;
        message += `Total Records: ${dataArray.length}\n`;
        message += `Columns: ${cols.join(', ')}\n\n`;
        message += `CSV Data:\n${csvData.substring(0, 500)}${csvData.length > 500 ? '\n...' : ''}`;

        const result = await Share.share({
            message: message,
            title: `${fileName} - Excel Export`,
        });

        if (result.action === Share.dismissedAction) {
            console.log('Share dismissed');
        }
    } catch (error) {
        console.error('Error exporting to Excel:', error);
        throw error;
    }
};

/**
 * Export data to CSV via Share API
 */
export const exportToCSV = async (
    data: any[],
    fileName: string,
    headers?: string[]
): Promise<void> => {
    try {
        const dataArray = Array.isArray(data) ? data : [data];
        const csvContent = convertToCSV(dataArray, headers);

        const result = await Share.share({
            message: `CSV Export: ${fileName}\n\nGenerated: ${new Date().toLocaleString()}\n\nData:\n${csvContent.substring(0, 500)}${csvContent.length > 500 ? '\n...' : ''}`,
            title: `${fileName} - CSV Export`,
        });

        if (result.action === Share.dismissedAction) {
            console.log('Share dismissed');
        }
    } catch (error) {
        console.error('Error exporting to CSV:', error);
        throw error;
    }
};

/**
 * Get CSV data as string (for clipboard or other uses)
 */
export const getCSVString = (data: any[], headers?: string[]): string => {
    return convertToCSV(data, headers);
};

/**
 * Get HTML data as string (for email or viewing)
 */
export const getHTMLString = (data: any, title: string): string => {
    return convertToHTML(data, title);
};
